# values.yaml
---
rabbitmq:
  image: rabbitmq:4.1.2-management
  containerName: local-rabbitmq
  resources: {}
    
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  storage:
    size: 1Gi
  livenessProbe:
    exec:
      command:
        - rabbitmq-diagnostics
        - check_port_connectivity
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5
    successThreshold: 1

  readinessProbe:
    exec:
      command:
        - rabbitmq-diagnostics
        - ping
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

postgres:
  image: postgres:17.5-bookworm
  imagePullPolicy: IfNotPresent
  replicas: 1
  resources: {}

worker:
  image: chineidu/rmq-worker:v1
  imagePullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
worker:
  image: chineidu/rmq-worker:v1
  imagePullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

worker:
  image: chineidu/rmq-worker:v1
  imagePullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

producer:
  image: chineidu/rmq-producer:v1
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
