app_config:
  data:
    data_path: data/train.parquet
    batch_data:
      is_remote: true
      remote_data_id: 1lSKBgYQ6bgV4ARRpeRfPMpLgf1GgyWY8
      download_path: data/downloaded_data.parquet
      batch_mode: true
      batch_size: 100
    num_vars:
      - age
      - pclass
      - sibsp
      - parch
      - fare
      - survived
    cat_vars:
      - sex
      - embarked

  db:
    db_path: db/results.db
    max_connections: 5

  model:
    hyperparams:
      n_splits: 5
      n_estimators: 100
      max_depth: 10
      random_state: 42
      test_size: 0.2

    artifacts:
      model_path: models/model.pkl
