apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s.fullname" . }}-api
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicas | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8s.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: api
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        command: {{ toYaml .Values.api.command | nindent 12 }}
        ports:
        - name: http
          containerPort: {{ .Values.api.service.port }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.config.configMapRef.name }}
        - secretRef:
            name: {{ .Values.config.secretRef.name }}
        {{- with .Values.api.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.api.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.api.resources | nindent 12 }}
        volumeMounts:
        {{- if .Values.api.volumes.data.enabled }}
        - name: app-data
          mountPath: {{ .Values.api.volumes.data.mountPath }}
        {{- end }}
        {{- if .Values.api.volumes.models.enabled }}
        - name: models-data
          mountPath: {{ .Values.api.volumes.models.mountPath }}
        {{- end }}
      volumes:
      {{- if .Values.api.volumes.data.enabled }}
      - name: app-data
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.appData.name }}
      {{- end }}
      {{- if .Values.api.volumes.models.enabled }}
      - name: models-data
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.modelsData.name }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
