apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s.fullname" . }}-flower
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: flower
spec:
  replicas: {{ .Values.flower.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "k8s.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: flower
  template:
    metadata:
      labels:
        {{- include "k8s.labels" . | nindent 8 }}
        app.kubernetes.io/component: flower
    spec:
      containers:
      - name: flower
        image: "{{ .Values.flower.image.repository }}:{{ .Values.flower.image.tag }}"
        imagePullPolicy: {{ .Values.flower.image.pullPolicy }}
        command: {{ toYaml .Values.flower.command | nindent 12 }}
        ports:
        - name: flower
          containerPort: 5555
        envFrom:
        - configMapRef:
            name: {{ .Values.config.configMapRef.name }}
        - secretRef:
            name: {{ .Values.config.secretRef.name }}
        resources:
          {{- toYaml .Values.flower.resources | nindent 12 }}
