apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s.fullname" . }}-rabbitmq
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "k8s.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "k8s.labels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
        imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        envFrom:
        - configMapRef:
            name: {{ .Values.config.configMapRef.name }}
        - secretRef:
            name: {{ .Values.config.secretRef.name }}
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_port_connectivity
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - check_port_connectivity
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        {{- if .Values.rabbitmq.configMount.enabled }}
        - name: rabbitmq-config
          mountPath: {{ .Values.rabbitmq.configMount.mountPath }}
          subPath: {{ .Values.rabbitmq.configMount.subPath }}
        {{- end }}
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.rabbitmqData.name }}
      {{- if .Values.rabbitmq.configMount.enabled }}
      - name: rabbitmq-config
        configMap:
          name: {{ .Values.rabbitmq.configMount.configMapName }}
      {{- end }}
